apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: springboot-demo-dev
  namespace: springboot-demo-dev
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: springboot-demo-dev
      app.kubernetes.io/name: springboot-demo
  namespaceSelector:
    matchNames:
      - springboot-demo-dev
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s