replicaCount: 1

image:
  repository: ghcr.io/arkly365/springboot-demo
  pullPolicy: IfNotPresent
  tag: "v2"

containerPort: 8080

imagePullSecrets:
  - name: ghcr-secret

readinessProbe:
  path: /actuator/health/readiness
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6

livenessProbe:
  path: /actuator/health/liveness
  initialDelaySeconds: 60
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6