replicaCount: 1

image:
  repository: ghcr.io/arkly365/springboot-demo
  pullPolicy: IfNotPresent
  tag: "v5"

containerPort: 8080

imagePullSecrets:
  - name: ghcr-secret

livenessProbe:
  httpGet:
    path: /actuator/health/liveness
    port: http
  initialDelaySeconds: 60
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6

readinessProbe:
  httpGet:
    path: /actuator/health/readiness
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6